### PR TITLE
Some baseline clean-up for the EA3 examples

### PR DESCRIPTION
**Pull request by jmakeig**

### CODE REVIEW

**Comment by jmakeig** [comment]
Oops that last commit, 19fecc8, should be in a separate PR.

**Comment by grechaw** [comment]
I'll layer all these commits within my own refactoring and add a couple more.  What should be done with 19fecc8?

**Comment by grechaw** [comment]
So I've just merged your commits into examples-refresh, but on top of the refactoring I've proposed.  I'm about to do some cleanup on this to make it all work again and upate the branch once more. 

At that point you'll probably want to rebase from develop and start a new unit of work.

**Comment by jmakeig** [comment]
I think we should use 19fecc8. It just wasn’t polite of me to include it in this PR with other, non-security stuff. (`<soapbox>`Philosophically I’d like to break us of the habit of running demos as admin. It’s worst practice and likely hides permissions/privilege corner cases.`</soapbox>`)

**Comment by grechaw** [comment]
Sounds good, in the new codegen extension ive added two new privileges to the race-admin guy (filesystem file and xdmp:save).

**Pull request closed without merging**
